"""

Problem
In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s
 is the string sc
 formed by reversing the symbols of s
, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s
 of length at most 1000 bp.

Return: The reverse complement sc
 of s
.

"""


dna_string = "CGCAACTCGCTCGTATTCATCGTGCGGTCATATGAGACGGCGACCACCAGACAAGACCTGTAAACTGCGGTGAATAAGCCCTCTTCGGGACTCTGACTTAAGCTAGCTGTTAGAACACAAGGGATCACATCGGGAATCTGAGAATCGCCCCCTCTTCGCCGGGAGCATTGTAGTGGTCCCATACCATGCGATGTGCTGAGAAACGAGCTCCACAGCGGGTAATAAAGAATAGTCTTGGCTAATTTTTAACACCGAACGCCGGGCCTCCTACTCTGAGCGCTTGCAGTGACACAGTTCTCACGCGTTACATCTCATGCGCATATAAACGGAAACCGCGGCTTTTCCTCATGAAAGACTACGTTTCCATACTACTTAGTATATAAGGTCGGTAGTGCGCCAATCAAGAGATGGCTGTAATTAGTGATAAACTTAAGGAGGATCACCCTTACGTACTCCCATGGCCTGAGAGGGGGTATACCTCGCTGCATATACTCTTTGATTGACTAAGCCCATCGATCAGGCTAGCACAGAGGATGCGTTCTGGCCAGGTACGAATTGACGTGTGATCGCGTAAAGCCGAGGTTTAGGTGAGAATGACCATAGAGTAGTGGACGGAACAGCATATTCCGGGCAGTTCTGCCCCACGGATGCCCGGGCCCACCTGAGGGTGCTTTAATTCACGCTTCTGCGTCTGTTTTGTATTTAGTCTGTCAGGACTGGGGGCACGGCCCTGTTTATGGTAATGTCTCAAGGTTAACGGTGAACCTTCATATGGATCCGTTCGATCTGCTAGTCCGTCGGCTTGAAGCCGCGTTCGTCACGATTCCGAATTCCTCTCCAAGCAATGCGCTACTCTGGGATGCTACGTATCTAGACGTAGGTTCTTGAGTCGTTAGAGGAAGCTTTCAGCTCAGGCTTAAACTGATCCAGGCTTGATGGGACTGCATAT"

dna_string = dna_string[::-1]
comp = []
for char in dna_string:
    if char == "A":
        comp.append("T")
    elif char == "T":
        comp.append("A")
    elif char == "G":
        comp.append("C")
    elif char == "C":
        comp.append("G")
compstr = "".join(comp)
print(compstr)

